# Generated by Django 4.2 on 2023-04-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_remove_product_id_alter_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
